version: '2'
services:
  eurekaserver:
    image: gfioritti/sbms-eurekasr:chapter7
    mem_limit: 512M
    ports:
    - 8761:8761
  configserver:
    image: gfioritti/sbms-confsvr:chapter7
    mem_limit: 512M
    ports:
    - 8888:8888
    environment:
      ENCRYPT_KEY: weerT55667SSdfg
      EUREKASERVER_URI: http://eurekaserver:8761/eureka/
      EUREKASERVER_PORT: '8761'
  zuulserver:
    image: gfioritti/sbms-zuulsvr:chapter7
    mem_limit: 512M
    ports:
    - 5555:5555
    environment:
      PROFILE: default
      SERVER_PORT: '5555'
      CONFIGSERVER_URI: http://configserver:8888
      EUREKASERVER_URI: http://eurekaserver:8761/eureka/
      EUREKASERVER_PORT: '8761'
      DATABASESERVER_PORT: '5432'
      CONFIGSERVER_PORT: '8888'
      ORGSERVERNEW_PORT: '8087'
  database:
    image: postgres:9.5
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres_dev
    - POSTGRES_PASSWORD=p0stgr@s_dev
    - POSTGRES_DB=eagle_eye_dev
  licensingservice:
    image: gfioritti/sbms-licensing-service:chapter8
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"
      ENCRYPT_KEY:       weerT55667SSdfg
  organizationservice:
    image: gfioritti/sbms-organization-service:chapter8
    mem_limit: 512M
    ports:
    - 8085:8085
    environment:
      PROFILE: default
      SERVER_PORT: '8085'
      CONFIGSERVER_URI: http://configserver:8888
      EUREKASERVER_URI: http://eurekaserver:8761/eureka/
      AUTHSERVER_URI: http://authenticationservice:8901/auth/user
      CONFIGSERVER_PORT: '8888'
      DATABASESERVER_PORT: '5432'
      EUREKASERVER_PORT: '8761'
      AUTHSERVER_URI_PORT: '8901'
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      KAFKASERVER_PORT:    "2181"
      ENCRYPT_KEY: weerT55667SSdfg
  orgservice-new:
    image: gfioritti/sbms-orgservice-new:chapter7
    mem_limit: 512M
    ports:
    - 8087:8087
    environment:
      PROFILE: default
      SERVER_PORT: '8087'
      CONFIGSERVER_URI: http://configserver:8888
      EUREKASERVER_URI: http://eurekaserver:8761/eureka/
      EUREKASERVER_PORT: '8761'
      DATABASESERVER_PORT: '5432'
      CONFIGSERVER_PORT: '8888'
      ENCRYPT_KEY: weerT55667SSdfg
  specialroutes-service:
    image: gfioritti/sbms-specialroutes-service:chapter7
    mem_limit: 512M
    ports:
    - 8910:8910
    environment:
      PROFILE: default
      SERVER_PORT: '8910'
      CONFIGSERVER_URI: http://configserver:8888
      EUREKASERVER_URI: http://eurekaserver:8761/eureka/
      EUREKASERVER_PORT: '8761'
      DATABASESERVER_PORT: '5432'
      CONFIGSERVER_PORT: '8888'
      ENCRYPT_KEY: weerT55667SSdfg
  authenticationservice:
    image: gfioritti/sbms-authentication-service:chapter7-jwt
    mem_limit: 512M
    ports:
    - 8901:8901
    environment:
      PROFILE: dev
      SERVER_PORT: '8901'
      CONFIGSERVER_URI: http://configserver:8888
      EUREKASERVER_URI: http://eurekaserver:8761/eureka/
      EUREKASERVER_PORT: '8761'
      DATABASESERVER_PORT: '5432'
      CONFIGSERVER_PORT: '8888'
      ENCRYPT_KEY: weerT55667SSdfg
  kafkaserver:
    image: spotify/kafka
    ports:
    - 2181:2181
    - 9092:9092
  redis:
    image: redis:alpine
    ports:
      - 6379:6379